### PR TITLE
EVG-17410: Add gzipping to logkeeper routes.

### PR DESCRIPTION
**Pull request by johndaniels**
This adds gzip to the major log returning routes, which should
substantially reduce their size.

### CODE REVIEW

**Comment by ybrill** [comment]
I just remembered: [evergreen uses a gzip middleware](https://github.com/evergreen-ci/evergreen/blob/eef4876f31be3579762f69400853904fdf358f0c/service/service.go#L50) that gzips the response [whenever it will be accepted](https://github.com/phyber/negroni-gzip/blob/c20bb8813a75c1595b380259d248c5d9a1739bb3/gzip/gzip.go#L115-L119). Should we consider using that instead?

**Comment by johndaniels** [comment]
Per conversation in Slack: Yes. Yes we should

**Review by julianedwards — APPROVED** [review]

**Comment by ybrill** [comment]
I think we could `go mod tidy` to make the dependency direct.

**Comment by ybrill** [comment]
Could it make sense to wrap everything in the handler (like in [the example in the readme](https://github.com/gorilla/handlers#example))?

**Comment by johndaniels** [comment]
@ybrill we could wrap everything... most of our non-log responses are tiny so I'm not sure it's much of a win if any if we gzip them though.

**Comment by ybrill** [comment]
sgtm

**Review by ybrill — APPROVED** [review]

**Pull request merged**
